# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in ba_beer_rating_1.gemspec
gemspec

gem "rake", "~> 13.0"
